name: ml-python
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - joblib
  - nltk
  - jupyter
  - jupyterlab
  - nodejs>5
  - pyemd
  - beautifulsoup4
  - dask
  - pip:
    - urlextract
    - modin[ray]